apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-logs-claim
  namespace: insights
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 2Gi
