apiVersion: v1
kind: Service
metadata:
  name: platformservice
  namespace: insights
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: http-service
  selector:
    app: platformservice
  type: LoadBalancer