version: '3.8'

services:
  postgres:
    image: devopsbasservice/onedevopsinsights:postgres12
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    env_file:
      - ./config.env
    volumes:
      - $VOL_PATH/InsightsData/postgres/data:/var/lib/postgresql/data
      - ./postgres/postgresql.conf:/etc/postgresql.conf
      - ./postgres/pg_hba.conf:/etc/pg_hba.conf
    ports:
      - 35432:5432
    command: postgres -c config_file=/etc/postgresql.conf -c hba_file=/etc/pg_hba.conf

  neo4j:
    image: neo4j:4.4.4-community
    volumes:
      - $VOL_PATH/InsightsData/neo4j/data:/data
      - $VOL_PATH/InsightsData/neo4j/logs:/logs
      - $VOL_PATH/InsightsData/neo4j/conf:/conf
    env_file:
      - ./config.env
    healthcheck:
      test: ["CMD", "cypher-shell", "match (n) return count(n)"]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 40s
    ports:
      - 7474:7474
      - 7687:7687

  grafana:
    image: devopsbasservice/onedevopsinsights:grafana10.0.0
    env_file:
      - ./config.env
    healthcheck:
      test: curl --fail -s http://localhost:30000/api/healthy || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
    volumes:
       - $VOL_PATH/InsightsData/grafana/logs:/usr/INSIGHTS_HOME/logs
    depends_on:
      - postgres
    ports:
      - 30000:3000
      - 31000:3100

  rabbitmq:
    image: devopsbasservice/onedevopsinsights:rabbitmq3.9
    volumes:
      - $VOL_PATH/InsightsData/rabbitmq/data:/var/lib/rabbitmq
      - $VOL_PATH/InsightsData/rabbitmq/log:/var/log/rabbitmq
    env_file:
      - ./config.env
    hostname: rabbitmqtest
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 10
    ports:
      - 5672:5672
      - 15672:15672
      - 25672:25672
      - 5671:5671


  service:
    image: devopsbasservice/onedevopsinsights:service$INSIGHTS_VERSION
    env_file:
      - ./config.env
    depends_on:
      - grafana
      - neo4j
      - rabbitmq
    volumes:
      -  $VOL_PATH/InsightsData/PlatformService/logs:/usr/INSIGHTS_HOME/logs
      -  serverconfig:/usr/INSIGHTS_HOME/.InSights
    ports:
      - 38080:8080
      - 38081:8081

  ui:
    image: devopsbasservice/onedevopsinsights:ui$INSIGHTS_VERSION
    env_file:
      - ./config.env
    depends_on:
      - service
    ports:
      - 38081:8081

  engine:
    image: devopsbasservice/onedevopsinsights:engine$INSIGHTS_VERSION
    depends_on:
      - neo4j
      - rabbitmq
    volumes:
      -  $VOL_PATH/InsightsData/engine/logs:/usr/INSIGHTS_HOME/logs
      -  serverconfig:/usr/INSIGHTS_HOME/.InSights
    env_file:
      - ./config.env

  agentwebhook:
    image: devopsbasservice/onedevopsinsights:agentwebhook$INSIGHTS_VERSION
    volumes:
      - $VOL_PATH/InsightsData/agentswebhook/data:/opt/insightsagents/PlatformAgents
      - $VOL_PATH/InsightsData/agentswebhook/logs:/usr/INSIGHTS_HOME/logs
      - agentinitscripts:/etc/init.d
    env_file:
      - ./config.env
    depends_on:
      - rabbitmq
    ports:
      - 8981:8981


volumes:
  serverconfig:
  agentinitscripts:

