apiVersion: v1
kind: Service
metadata:
  name: platformui
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: http-ui
  selector:
    app: platformui
  sessionAffinity: None
  type: LoadBalancer