apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  ports:
    - port: 3000
      name: http-grafana
      protocol: TCP
      targetPort: http-grafana
    - port: 3100
      name: http-loki
      protocol: TCP
      targetPort: http-loki
  selector:
    app: grafana
  sessionAffinity: None
  type: LoadBalancer
