{
 "title": "Build Maturity",
 "time": { "from": "now-2y", "to": "now" },
 "templating": {
  "list": [
   { "name": "sprintId", "query": "ST-102" }
  ]
 },
 "panels": [
  { "title": "SCM", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Repo Type in $Portfolio",
   "type": "table",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "target": "MATCH (n:GIT) where exists(n.repoType) and n.Portfolio in $Portfolio  RETURN n.repoType as RepoType, count(n.repoType) as Count , n.Portfolio as Portfolio"
    }
   ]
  },
  {
   "title": "Scm Tool Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "cacheVariance": 5,
     "selectionval": "Variance Time",
     "target": "MATCH (n:GIT:DATA) where ?START_TIME?<=n.inSightsTime <=?END_TIME? with distinct labels(n) as l \nwith l as l,\ncount(l) as count\nunwind l as ScmTools\nwith ScmTools,sum(count) as count\nwhere not ScmTools in ['SCM', 'DATA', 'RAW'] return sum(count)"
    }
   ]
  },
  {
   "title": "SCM Commits",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 13, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "cacheVariance": 5,
     "selectionval": "Variance Time",
     "target": "MATCH (n:JIRA{sprintId:\"ST-102\"})-[:FROM_JIRA_TO_GIT]->(m:GIT) where ?START_TIME?<=n.inSightsTime <=?END_TIME? WITH distinct n.jiraKey as jiraKey   return count(jiraKey )"
    }
   ]
  },
  {
   "title": "Orphan Commits ",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "cacheVariance": 5,
     "selectionval": "Variance Time",
     "target": "MATCH (n:JENKINS:DATA) where ?START_TIME?<=n.inSightsTime <=?END_TIME? and exists(n.buildNumber) and not()-[]->() return count(n) as orphanCommits"
    }
   ]
  },
  { "title": "CI & CD", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CI Builds",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "cacheVariance": 5,
     "selectionval": "Variance Time",
     "target": "MATCH (n:JIRA{sprintId:\"ST-102\"})-[:FROM_JIRA_TO_GIT]->(m:GIT)  WITH distinct m as git\nMATCH (git)-[:FROM_GIT_TO_JENKINS]->(n:JENKINS) with distinct n.buildNumber as jenkins return count(jenkins)"
    }
   ]
  },
  {
   "title": "Avg. Build Time in Secs",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 3, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "cacheVariance": 5,
     "selectionval": "Variance Time",
     "target": "MATCH (n:JIRA)-[:FROM_JIRA_TO_GIT]->(m:GIT)  WHERE n.sprintId IN $sprintId WITH distinct m as git\nMATCH (git)-[:FROM_GIT_TO_JENKINS]->(n:JENKINS) with distinct n.duration  as Duration return ceil(avg(toInt(Duration ))) as AvgTimeInSecs"
    }
   ]
  },
  {
   "title": "CI Builds With CD",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 7, "y": 6 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "target": "MATCH (n2:RUNDECK)  WHERE ()-[:RUNDECK_TRG_BY_JENKINS]->(n2:RUNDECK)  return count(n2) as ManualDeployment"
    }
   ]
  },
  {
   "title": "Broken Build",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 10, "y": 6 },
   "format": "s",
   "valueName": "total",
   "targets": [
    {
     "cacheVariance": 5,
     "selectionval": "Variance Time",
     "target": "MATCH (n2:JENKINS:DATA) where ?START_TIME?<=n2.inSightsTime <=?END_TIME? and exists(n2.buildNumber) and exists(n2.buildUrl)  return count(n2)"
    }
   ]
  },
  {
   "title": "CI Build Trend by Status",
   "type": "insightscharts",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 6 },
   "targets": [
    {
     "target": "match (n:JENKINS) where n.status='Failure' AND n.buildNumber in $buildNumber return n.inSightsTimeX as inSightsTimeX, count(n) as Failed order by inSightsTimeX"
    },
    {
     "target": "match (n:JENKINS) where n.status='Success' AND n.buildNumber in $buildNumber return n.inSightsTimeX as inSightsTimeX, count(n) as Success order by inSightsTimeX"
    }
   ]
  },
  {
   "title": "Deployment",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "cacheVariance": 5,
     "selectionval": "Variance Time",
     "target": "MATCH (n:JIRA)-[:FROM_JIRA_TO_GIT]->(m:GIT)  WHERE n.sprintId IN $sprintId WITH distinct m as git\nMATCH (git)-[:FROM_GIT_TO_JENKINS]->(n:JENKINS) WITH distinct n as jenkins\nMATCH (jenkins)-[:FROM_JENKINS_TO_RUNDECK]->(n:RUNDECK) with distinct n.jenkineBuildNumber as Deployments return count(Deployments) as Count"
    }
   ]
  },
  {
   "title": "Avg. Deploy Time in Secs",
   "type": "insightscharts",
   "gridPos": { "h": 7, "w": 4, "x": 3, "y": 12 },
   "targets": [
    {
     "target": "match (n:RUNDECK) where n.jenkineBuildNumber in $jenkineBuildNumber return ceil(avg(toInt(n.jenkineBuildNumber))) as Deploy"
    }
   ]
  },
  {
   "title": "Manual Deployment",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 7, "y": 12 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "target": "MATCH (n2:RUNDECK)  WHERE NOT ()-[:FROM_JENKINS_TO_RUNDECK]->(n2:RUNDECK)  return count(n2) as ManualDeployment"
    }
   ]
  },
  {
   "title": "Deployment Trend by Status",
   "type": "insightscharts",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 12 },
   "targets": [
    {
     "target": "match (n:RUNDECK) where n.status='Failure' AND n.jenkineBuildNumber in $jenkineBuildNumber return n.inSightsTimeX as inSightsTimeX, count(n) as Failed order by inSightsTimeX"
    },
    {
     "target": "match (n:RUNDECK) where n.status='Success' AND n.jenkineBuildNumber in $jenkineBuildNumber return n.inSightsTimeX as inSightsTimeX, count(n) as Success order by inSightsTimeX"
    }
   ]
  },
  { "title": "CODEQUALITY", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Total Codequality Execution",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 20 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "cacheVariance": 5,
     "selectionval": "Variance Time",
     "target": "match(n:SONAR:DATA) where ?START_TIME?<=n.inSightsTime <=?END_TIME? return count(distinct(n)) as total"
    }
   ]
  },
  {
   "title": "Codequality Execution with CI",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 20 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "cacheVariance": 5,
     "selectionval": "Variance Time",
     "target": "MATCH (n:SONAR) \nwhere  EXISTS( ()-[:FROM_JENKINS_TO_SONAR]-(n:SONAR) ) and tofloat(n.inSightsTime)>=?START_TIME? AND tofloat(n.inSightsTime)<?END_TIME?\nreturn count(n) as Related"
    }
   ]
  },
  {
   "title": "CI Without Code Quality",
   "type": "graph",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {}
   ]
  }
 ]
}