{
 "title": "Builds",
 "time": { "from": "now-1y", "to": "now" },
 "panels": [
  {
   "title": "Build Inference",
   "type": "inference_panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Commits",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "cacheVariance": 5,
     "selectionval": "Variance Time",
     "target": "MATCH (n:JENKINS:DATA) RETURN count(n.scmcommitId) as TotalCommits"
    }
   ]
  },
  {
   "title": "No. of Commits/Developer",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "CommitUserName",
       "id": "3",
       "settings": { "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "inSightsTimeX", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "_type:SCM",
     "timeField": "inSightsTimeX"
    }
   ]
  },
  {
   "title": "Total Builds",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 15 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "inSightsTimeX", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "cacheVariance": 5,
     "metrics": [
      {
       "field": "CommitUserID",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "_type:SPKDATA AND SPKtoolName:JENKINS",
     "selectionval": "Variance Time",
     "target": "MATCH (n:JENKINS:DATA) RETURN count(n.buildNumber) as TotalCommits",
     "timeField": "inSightsTimeX"
    }
   ]
  },
  {
   "title": "Average Build Time(s)",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 15 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "inSightsTimeX", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "cacheVariance": 5,
     "metrics": [
      {
       "field": "CommitUserID",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "_type:SPKDATA AND SPKtoolName:JENKINS",
     "selectionval": "Variance Time",
     "target": "match (n:JENKINS) where n.toolName=\"JENKINS\" return ceil(avg(toInt(n.duration/60))) as AvgTimeInSecs",
     "timeField": "inSightsTimeX"
    }
   ]
  },
  {
   "title": "Build Frequency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {}
   ]
  },
  {
   "title": "Build Success vs Failure",
   "type": "insightscharts",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 22 },
   "targets": [
    {
     "target": "match (n:JENKINS) where n.status=\"Success\" AND n.toolName=\"JENKINS\" return n.inSightsTimeX as inSightsTimeX, count(n) as Success order by  inSightsTimeX"
    },
    {
     "target": "match (n:JENKINS) where n.status=\"Failure\" AND n.toolName=\"JENKINS\" return n.inSightsTimeX as inSightsTimeX, count(n) as Failed order by  inSightsTimeX"
    },
    {
     "target": "match (n:JENKINS) where n.status=\"Aborted\" AND n.toolName=\"JENKINS\" return n.inSightsTimeX as inSightsTimeX, count(n) as Abort order by  inSightsTimeX"
    }
   ]
  },
  {
   "title": "Build Status",
   "type": "insightscharts",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 22 },
   "targets": [
    {
     "cacheVariance": 5,
     "selectionval": "Variance Time",
     "target": "match (n:DATA)  where n.toolName=\"JENKINS\" return DISTINCT n.status as Status,count(n) as Count"
    }
   ]
  }
 ]
}