{
 "title": "Sprint Score Card",
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "SprintID",
    "query": "MATCH (n:JIRA) RETURN n.sprintId"
   }
  ]
 },
 "panels": [
  {
   "title": "SprintID",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "cacheVariance": 5,
     "selectionval": "Variance Time",
     "target": "match (n:JIRA) where n.sprintId in $SprintID return DISTINCT n.sprintId"
    }
   ]
  },
  {
   "title": "User Story",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "cacheVariance": 5,
     "selectionval": "Variance Time",
     "target": "match (n:JIRA) where n.sprintId in $SprintID return count(n) as Count"
    }
   ]
  },
  {
   "title": "SCM Commits",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "cacheVariance": 5,
     "selectionval": "Variance Time",
     "target": "match (a:JIRA)-[r:FROM_JIRA_TO_GIT]->(b:GIT) where a.sprintId in $SprintID with count(DISTINCT b.commitId) as Count  return Count"
    }
   ]
  },
  {
   "title": "Files Committed",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "cacheVariance": 5,
     "selectionval": "Variance Time",
     "target": "match (a:JIRA)-[r:FROM_JIRA_TO_GIT]->(b:GIT) where a.sprintId in $SprintID with count(b) as Count match (a:JIRA)-[r:FROM_JIRA_TO_GIT]->(b:GIT) where a.sprintId in $SprintID return count(b)+Count as Total"
    }
   ]
  },
  {
   "title": "CI Builds",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "cacheVariance": 5,
     "selectionval": "Variance Time",
     "target": "MATCH (n:JIRA)-[:FROM_JIRA_TO_GIT]->(m:GIT)  WHERE n.sprintId IN $SprintID WITH distinct m as git\nMATCH (git)-[:FROM_GIT_TO_JENKINS]->(n:JENKINS) with distinct n.buildNumber as buildNumber return count(buildNumber) as Count"
    }
   ]
  },
  {
   "title": "Deployment",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "cacheVariance": 5,
     "selectionval": "Variance Time",
     "target": "MATCH (n:JIRA)-[:FROM_JIRA_TO_GIT]->(m:GIT)  WHERE n.sprintId IN $SprintID WITH distinct m as git\nMATCH (git)-[:FROM_GIT_TO_JENKINS]->(n:JENKINS) WITH distinct n as jenkins\nMATCH (jenkins)-[:FROM_JENKINS_TO_RUNDECK]->(n:RUNDECK) with distinct n.jenkineBuildNumber as Deployments return count(Deployments )"
    }
   ]
  },
  {
   "title": "Developers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "cacheVariance": 5,
     "selectionval": "Variance Time",
     "target": "match (a:JIRA)-[r:FROM_JIRA_TO_GIT]->(b:GIT) where a.sprintId in $SprintID return count(DISTINCT b.gitAuthorName) as Count"
    }
   ]
  },
  {
   "title": "Defects",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "match (n:DEFECTS) where n.SprintID in $SprintID return count(n) as Count"
    }
   ]
  },
  {
   "title": "Defects Type",
   "type": "table",
   "gridPos": { "h": 6, "w": 5, "x": 3, "y": 4 },
   "targets": [
    {
     "target": "match (n:DEFECTS) where n.SprintID in $SprintID return DISTINCT n.DefectDuring as Type, count(n) as Count order by Count desc"
    }
   ]
  },
  {
   "title": "Top Commit Users",
   "type": "insightscharts",
   "gridPos": { "h": 6, "w": 10, "x": 8, "y": 4 },
   "targets": [
    {
     "cacheVariance": 5,
     "selectionval": "Variance Time",
     "target": "match (a:JIRA)-[r:FROM_JIRA_TO_GIT]->(b:GIT)  where a.sprintId in $SprintID return DISTINCT b.gitAuthorName as Developer, count(DISTINCT b.gitCommitId) as Count order by Count desc limit 5"
    }
   ]
  },
  {
   "title": "Defect Assignees",
   "type": "insightscharts",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 4 },
   "targets": [
    {
     "target": "match (a:DEFECTS) where a.SprintID in $SprintID return DISTINCT a.AssignedTo as Developer, count(a.DefectID) as Count order by Count desc limit 5"
    }
   ]
  },
  {
   "title": "Average Time In Seconds",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "cacheVariance": 5,
     "selectionval": "Variance Time",
     "target": "MATCH (n:JIRA)-[:FROM_JIRA_TO_GIT]->(m:GIT)  WHERE n.sprintId IN $SprintID WITH distinct m as git\nMATCH (git)-[:FROM_GIT_TO_JENKINS]->(n:JENKINS) with distinct n.duration  as Duration return ceil(avg(toInt(Duration ))) as AvgTimeInSecs"
    }
   ]
  },
  {
   "title": "Max. Build Time in Secs",
   "type": "insightscharts",
   "gridPos": { "h": 7, "w": 5, "x": 4, "y": 10 },
   "targets": [
    {
     "cacheVariance": 5,
     "selectionval": "Variance Time",
     "target": "MATCH (n:JIRA)-[:FROM_JIRA_TO_GIT]->(m:GIT)  WHERE n.sprintId IN $SprintID WITH distinct m as git\nMATCH (git)-[:FROM_GIT_TO_JENKINS]->(n:JENKINS) with distinct n.duration  as Duration return ceil(max(toInt(Duration ))) as Build"
    }
   ]
  },
  {
   "title": "CI Build Trend by Status",
   "type": "insightscharts",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 10 },
   "targets": [
    {
     "cacheVariance": 5,
     "selectionval": "Variance Time",
     "target": "MATCH (n:JIRA)-[:FROM_JIRA_TO_GIT]->(m:GIT)  WHERE n.sprintId in $SprintID WITH distinct m as git\nMATCH (git)-[:FROM_GIT_TO_JENKINS]->(n:JENKINS) WHERE n.status=\"Failure\" WITH distinct n.buildNumber as buildNumber  return buildNumber.inSightsTimeX as inSightsTimeX, count(buildNumber) as Failed order by inSightsTimeX"
    },
    {
     "cacheVariance": 5,
     "selectionval": "Variance Time",
     "target": "MATCH (n:JIRA)-[:FROM_JIRA_TO_GIT]->(m:GIT)  WHERE n.sprintId in $SprintID WITH distinct m as git\nMATCH (git)-[:FROM_GIT_TO_JENKINS]->(n:JENKINS) WHERE n.status=\"Success\" WITH distinct n.buildNumber as buildNumber  return buildNumber.inSightsTimeX as inSightsTimeX, count(status) as Success order by inSightsTimeX"
    }
   ]
  },
  {
   "title": "Average Time In Seconds",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 17 },
   "format": "d",
   "valueName": "avg",
   "targets": [
    {
     "target": "match (n:RUNDECK) where n.jenkineBuildNumber in $buildNumber return ceil(avg(toInt(n.jenkineBuildNumber))) as AvgTimeInSecs"
    }
   ]
  },
  {
   "title": "Max. Deploy Time in Secs",
   "type": "insightscharts",
   "gridPos": { "h": 7, "w": 5, "x": 4, "y": 17 },
   "targets": [
    {
     "target": "match (n:RUNDECK) where n.jenkineBuildNumber in $buildNumber return ceil(max(toInt(n.duration))) as Deploy"
    }
   ]
  },
  {
   "title": "Deployment Trend by Status",
   "type": "insightscharts",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 17 },
   "targets": [
    {
     "cacheVariance": 5,
     "selectionval": "Variance Time",
     "target": "MATCH (n:JIRA)-[:FROM_JIRA_TO_GIT]->(m:GIT)  WHERE n.sprintId IN $SprintID WITH distinct m as git\nMATCH (git)-[:FROM_GIT_TO_JENKINS]->(n:JENKINS) WITH distinct n as jenkins\nMATCH (jenkins)-[:FROM_JENKINS_TO_RUNDECK]->(n:RUNDECK) where n.status='Failure' with distinct n.jenkineBuildNumber as Deployments return n.inSightsTimeX as inSightsTimeX, count(Deployments) as Failed order by inSightsTimeX"
    },
    {
     "cacheVariance": 5,
     "selectionval": "Variance Time",
     "target": "MATCH (n:JIRA)-[:FROM_JIRA_TO_GIT]->(m:GIT)  WHERE n.sprintId IN $SprintID WITH distinct m as git\nMATCH (git)-[:FROM_GIT_TO_JENKINS]->(n:JENKINS) WITH distinct n as jenkins\nMATCH (jenkins)-[:FROM_JENKINS_TO_RUNDECK]->(n:RUNDECK) where n.status='Success' with distinct n.jenkineBuildNumber as Deployments return n.inSightsTimeX as inSightsTimeX, count(Deployments) as Success order by inSightsTimeX"
    }
   ]
  }
 ]
}