{
 "title": "Code Quality",
 "time": { "from": "now-1y", "to": "now" },
 "panels": [
  {
   "title": "Code Quality Inference",
   "type": "inference_panel",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Sonar Executions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "cacheVariance": 5,
     "selectionval": "Variance Time",
     "target": "match (n:DATA) WHERE n.toolName=\"SONAR\" return toInt(n.inSightsTime/(((?END_TIME?-?START_TIME?)/100)))*((?END_TIME?-?START_TIME?)/100),  count(distinct n), n.resourceKey"
    }
   ]
  },
  {
   "title": "Quality Gate Status",
   "type": "insightscharts",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "cacheVariance": 5,
     "selectionval": "Variance Time",
     "target": "match (n:SONAR{sonarQualityGateStatus: \"FAILED\",toolName: \"SONAR\"})  return n.inSightsTimeX as inSightsTimeX, count(n) as Failed order by  inSightsTimeX"
    },
    {
     "cacheVariance": 5,
     "selectionval": "Variance Time",
     "target": "match  (n:SONAR{sonarQualityGateStatus: \"SUCCESS\",toolName: \"SONAR\"})  return n.inSightsTimeX as inSightsTimeX, count(n) as Success order by  inSightsTimeX"
    }
   ]
  },
  {
   "title": "Coverage Trend",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "cacheVariance": 5,
     "selectionval": "Variance Time",
     "target": "match (n:DATA) where n.toolName=\"SONAR\" return toInt(n.inSightsTime/(((?END_TIME?-?START_TIME?)/100)))*((?END_TIME?-?START_TIME?)/100), round(ceil(avg(toInt(n.sonarCoverage)))), n.resourceKey"
    }
   ]
  },
  {
   "title": "CodeSmells Trend",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "inSightsTimeX", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "SPKcodeSmells",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "_type:SPKDATA AND SPKtoolName:SONAR",
     "timeField": "inSightsTimeX"
    }
   ]
  },
  {
   "title": "Bugs Trend",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "inSightsTimeX", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "SPKbugs",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "_type:SPKDATA AND SPKtoolName:SONAR",
     "timeField": "inSightsTimeX"
    }
   ]
  },
  {
   "title": "Complexity Trend",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "inSightsTimeX", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "cacheVariance": 5,
     "metrics": [
      {
       "field": "SPKcomplexity",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "_type:SPKDATA AND SPKtoolName:SONAR",
     "selectionval": "Variance Time",
     "target": "match (n:DATA) where n.toolName=\"SONAR\" return toInt(n.inSightsTime/(((?END_TIME?-?START_TIME?)/100)))*((?END_TIME?-?START_TIME?)/100), round(ceil(avg(toInt(n.sonarComplexity)))), n.resourceKey",
     "timeField": "inSightsTimeX"
    }
   ]
  },
  {
   "title": "Blockers Trend",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "inSightsTimeX", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "SPKblockers",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "_type:SPKDATA AND SPKtoolName:SONAR",
     "timeField": "inSightsTimeX"
    }
   ]
  },
  {
   "title": "TechnicalDebt Trend",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {}
   ]
  },
  {
   "title": "Major Minor Info Trend",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "inSightsTimeX", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "SPKmajors",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "SPKminors",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "SPKinfos",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "_type:SPKDATA AND SPKtoolName:SONAR",
     "timeField": "inSightsTimeX"
    }
   ]
  },
  {
   "title": "Criticals Trend",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "inSightsTimeX", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "SPKcriticals",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "_type:SPKDATA AND SPKtoolName:SONAR",
     "timeField": "inSightsTimeX"
    }
   ]
  },
  {
   "title": "Duplication % Trend",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "inSightsTimeX", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "SPKduplication",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "_type:SPKDATA AND SPKtoolName:SONAR",
     "timeField": "inSightsTimeX"
    }
   ]
  },
  {
   "title": "Resolution Trend",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "inSightsTimeX", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "SPKfalsePositive",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "SPKfixed",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "SPKunresolved",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "SPKwontFix",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "_type:SPKDATA AND SPKtoolName:SONAR",
     "timeField": "inSightsTimeX"
    }
   ]
  },
  {
   "title": "Vulnerabilities Trend",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "inSightsTimeX", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "SPKvulnerabilities",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "_type:SPKDATA AND SPKtoolName:SONAR",
     "timeField": "inSightsTimeX"
    }
   ]
  },
  {
   "title": "UnitTesting Trend",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "inSightsTimeX", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "SPKtestFailed",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "SPKtotalUnitTestcases",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "_type:SPKDATA AND SPKtoolName:SONAR",
     "timeField": "inSightsTimeX"
    }
   ]
  },
  {
   "title": "Maintainability Trend",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 107 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "SPKmaintainability",
       "id": "4",
       "settings": { "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "inSightsTimeX", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "SPKtotalUnitTestcases",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "_type:SPKDATA AND SPKtoolName:SONAR",
     "timeField": "inSightsTimeX"
    }
   ]
  },
  {
   "title": "Reliability Trend",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 114 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "SPKreliability",
       "id": "4",
       "settings": { "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "inSightsTimeX", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "SPKtotalUnitTestcases",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "_type:SPKDATA AND SPKtoolName:SONAR",
     "timeField": "inSightsTimeX"
    }
   ]
  },
  {
   "title": "Security Trend",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 121 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "SPKsecurity",
       "id": "4",
       "settings": { "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "inSightsTimeX", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "SPKtotalUnitTestcases",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "_type:SPKDATA AND SPKtoolName:SONAR",
     "timeField": "inSightsTimeX"
    }
   ]
  }
 ]
}