{
 "title": "SCM Dashboard1",
 "time": { "from": "now-1y", "to": "now" },
 "panels": [
  {
   "title": "Total GitHub Commits",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "MATCH (n:GIT:DATA) where ?START_TIME?<=n.inSightsTime <=?END_TIME? RETURN count(n) as TotalCommits"
    }
   ]
  },
  {
   "title": "Commits Frequency",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "target": "match (n:GIT:DATA) where ?START_TIME?<=n.inSightsTime<=?END_TIME?  return distinct(split(n.inSightsTimeX,\"T\")[0]) as inSightsTimeX, count(n) as commits order by  inSightsTimeX"
    }
   ]
  },
  {
   "title": "Detailed Commits Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "target": "MATCH (n:GIT:DATA) where ?START_TIME?<=n.inSightsTime <=?END_TIME? return n.repoName as Repo, n.commitId as Commit, n.gitAuthorName as Author, n.gitCommiTime as CommitDate order by CommitDate desc limit 5"
    }
   ]
  }
 ]
}